Initial implementation
clearbit/clearbit-go pull request #1
Opened 2016-11-13 00:57 UTC by maccman

2016-11-13 01:37 UTC, harlow commented on README.md
> +  results, resp, _ := client.Reveal.Find(clearbit.RevealFindParams{
Don't ignore errors!! Should always look for non-nil error

2016-11-13 01:37 UTC, harlow commented on README.md
> +  client := clearbit.NewClient(nil, os.Getenv("CLEARBIT_KEY"))
Feels a little odd having to pass in Nil here. Could make a config struct that has sensible defaults?

2016-11-13 01:44 UTC, lazyatom requested changes
Where are the tests? ;-)

2016-11-14 18:12 UTC, harlow commented on clearbit/autocomplete.go
> +
We should add comments to anything with uppercase. That way the Godocs will generate correctly:

```go
// AutocompleteService autocompletes a company name based on partial text.
type AutocompleteService struct {
```

2016-11-14 18:25 UTC, maccman commented on README.md
> +  client := clearbit.NewClient(nil, os.Getenv("CLEARBIT_KEY"))
@dcadenas let's improve the config - maybe take a ClearbitConfig object that let's you set the APIKey and defaults back to pulling out the key from ENV.

2016-11-16 18:55 UTC, maccman commented
lgtm - merge away!

2016-11-16 20:55 UTC, merged